### ISSUE TITLE
Can't scrape certain Turbografx games (e.g. Bonk 2, 3) that are in the screenscraper.fr site

### ISSUE THREAD

**Issue by OrlandoPete** [Universal-Rom-Tools/Universal-XML-Scraper#176] opened 2017-02-22 23:29 UTC
Hi, I have had success with all of my Genesis games and some Sega CD games, but with Turbografx I have found a few where it will not pull down the data or images even through they exist on screenscraper.fx. I don't know if I need to try new file names or something else? They are:

Bonk's Revenge
Bonk III - Bonk's Big Adventure (Turbo CD version)
Devil's Crush

Any ideas?

**Comment by Universal-Rom-Tools** [comment] 2017-02-23 13:52
We need to work on these DB :S 
TurbografX, CoregrafX I and II, and PC Engine are exactly the same plateform (difference are country based with some change in the color or formfactor the console have)...

We need to merge them in 1 clean DB (like we do with Neogeo AES and MVS)

For now, I maybe have a solution (not the best one :S )

In General Config menu, Uncheck the "Automatic plateform Selection" Checkbox.
So when scrape begin it will ask you in wich plateform DB you want to scrape.
Scrape 1 time in TurbografX
When finish, Back in the config menu, choose "Update" in scrape mode
and Scrape in CoregrafX I
and Scrape in CoregrafX II
and Scrape in PC Engine

Really not the best way to do this :S but I think it will work till we merge all of that...

**Comment by morgalion** [comment] 2017-02-23 13:59
I can confirm, it worked for me ;)

**Comment by morgalion** [comment] 2017-02-23 14:07
But one more advice, try to search your game hashes (md5), of your missing.txt in screenscrapper (rom search form) ;)
3 solutions : 
- Rom found but not associated : you can associate it to a game and contribute ;)
- Rom not found at all: contact SS team
- Rom and game found/associated : verify UXS options

This check is more accurate that checking rom's namefile in SS.

**Comment by OrlandoPete** [comment] 2017-02-23 15:04
Thank you for the suggestions! Question on update mode...will it attempt to update your image to the one on screenscraper.fr even if you already have an image associated with the game in gamelist.xml from a different scraper? What is the best procedure to get it to update the image?

**Comment by morgalion** [comment] 2017-02-23 15:26
As far as i know, UXS only scrape games that are not presents in your gamefile.xml, with update option.
If the game is already present in gamefile.xml, nothing will be updated.
It's more like a "add mode" rather than "update mode" for roms. the "update" word means no gamelist.xml file will be recreated ;)

**Comment by OrlandoPete** [comment] 2017-02-23 15:40
Okay yeah, that's what I figured. It's weird because I ran an update once yesterday trying to get Devil's Crush and Bonk 2+3, and it updated my Bonk's Adventure image from the US version to the Japanese version. Not sure why that happened. So I removed the game entirely from the gamelist.xml, removed the image from the folder, ran a re-scrape and...nothing. It didn't put Bonk's Adventure back in at all even though that was one game that it did successfully find the first time i ran the scrape.

**Comment by morgalion** [comment] 2017-02-23 15:50
Can you send your missing.txt ?

**Comment by OrlandoPete** [comment] 2017-02-23 17:56
Yeah I can do that. I will try the suggestions above first and see where that gets me. Thanks for the help!

**Comment by OrlandoPete** [comment] 2017-02-24 12:59
I tried the suggestion above to re-scrape all of they systems separately, and I still can't get Bonk 2, 3, and Devil's Crush. Legenday Axe 1 + 2 are also not found, and I just found those in the SS site. Before I was looking in "L" but they are actually in "T" for THE Legendary Axe. Maybe I need to add "The" to my file name? So, I have 5 games missing that should be there. I attached my missing.txt, and also pasted the contents below.

[_PC Engine_missing.txt](https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/files/799292/_PC.Engine_missing.txt)

Bonk III - Bonk's Big Adventure.cue                                 1A27FC42              821    18:27.00 2016-08-14    0E26076494FB1F8361269D9DEDF55AC4
Bonk's Revenge.PCE                                                  76B521AC          524 800    18:02.00 1995-06-06    71BE903475F3557A7E4FBD956E3C78A3
Devil's Crush.PCE                                                   2762792B          524 288    15:05.00 1997-05-30    D9F5E1A621EA511ACDB6DE77785D3BC0
Dungeon Explorer II.cue                                             C4FA690E            1 506    21:49.00 2016-08-13    AC13EB695725BB623D185733D2338FBC
Legendary Axe 2.PCE                                                 C3A1FB28          262 656    16:00.00 1990-01-01    CAF33CD59FA1E8DB148D82BCC8AEDF1B
Legendary Axe.PCE                                                   BB2CA3ED          262 656    23:18.00 1997-04-10    1F374E7595E50B443957B877C3240528

**Comment by morgalion** [comment] 2017-02-24 13:45
1 advice : don't care of name but md5 hash ;) you can look for md5 hash in SS rom search form (you can find corresponding md5 hash of your roms in missing.txt, last column). It's better to precisely look for your rom version. (and checkyou have the option name+hash in ss to look for game).

For example, i checked your missing.txt, no one of your hashes are present in SS base, so you can't find them, at least with hash+name option.
It sometimes happens when roms are not from a well known set/team. And it also happens for .cue files when there are home made and not the ones delivered with roms (and sometimes they are just not added in database) ;)
So 3 solutions: 
1) You are sure that your rom is a good one, so contact SS team (irc, forum, and here maybe ^^), they will add your rom in database
2) Find a better version of the rom (you can have name and hash of already known roms version in SS's game page)
3) Just rename exactly as an existing rom and choose the ss option "name only" to look for game (but i dislike this option ... because it doesn't help SS project, not very sure etc...), so only if the 2 last solutions are not possible :)

I hope it helps

**Comment by OrlandoPete** [comment] 2017-02-24 15:58
Ah, ok I see how it works now. How do I search the screenscraper.fr site with a hash number? I see the search boxes, but no option for name+hash.

Second, if I know a hash that works, I assume it's just finding a rom with that hash. I was using a certain site that is like paradise. Any suggestions for a better one?

**Comment by morgalion** [comment] 2017-02-24 16:09
> Ah, ok I see how it works now. How do I search the screenscraper.fr site with a hash number?
There is 1 textbox to search "games" and 1 to search "roms", use the second one (you need to be logged in to see it, upper right)

> Second, if I know a hash that works, I assume it's just finding a rom with that hash. I was using a certain site that is like paradise. Any suggestions for a better one?
I'm not sure we can help you for legal reasons. But a good start with team names : look for no-intro sets for consoles, TOSEC for small computers, redump and trurip team for CD-based systems

**Comment by morgalion** [comment] 2017-02-24 16:22
But of course, if you think your rom has his place in SS database, feel free to send *_missing.txt to admins of SS. But they will ask you the rom team/source, to ensure the quality of it (because they don't want home made roms in DB, it's not the goal ;) )

**Comment by Universal-Rom-Tools** [comment] 2017-03-12 22:21
nothing to say ^^ Thank you @morgalion ^^

(I close the issue so..)

**Closed by Universal-Rom-Tools** 2017-03-12 22:21 UTC
Labels: question, Screenscraper
