### ISSUE TITLE
UXS stopped creating gamelist.xml and images

### ISSUE THREAD

**Issue by verybadsoldier** [Universal-Rom-Tools/Universal-XML-Scraper#51] opened 2016-11-25 18:07 UTC
I tried UXS today with some systems to scrape ROM sets for my RetroPie setup. But currently UXS stopped creating gamelist.xml and downloading images at all.
I configured everything as I want it to be (and I think it already worked with that config) but when I press "Scrape" it finishes really quickly and says "roms found 3/3" (I created a test set with only 3 roms). But then there are no downloaded images and also no gamelist.xml at all. Any help please?

This is the log:
http://pastebin.com/zDB9M25s

Anything else I could provide or try to find the cause? Thanks!

EDIT:
`_Atari ST_missing.txt` gets created in the ROM folder but is 0 byte size.

**Comment by AnthraxLeprosyPi** [comment] 2016-11-25 18:30
Just tried Atari 5200 - works on my behalf with the latest version and fresh config...

Using RecalBox 4 Mix profile.

**Comment by verybadsoldier** [comment] 2016-11-25 19:09
Found more logs in log1.txt from the actual downloader:
```
[20:06:23] - > -In 3 try and 0.83s
[20:06:23] - /!\ Error Downloading File : \\wz-retro\roms\..\configs\all\emulationstation\downloaded_images\atarist\Adidas Championship Tie Break (Europe)-image.jpg
[20:06:23] - /!\ Bytes read: 0
[20:06:23] - /!\ Size: 0
[20:06:23] - /!\ Complete: True
[20:06:23] - /!\ successful: False
[20:06:23] - /!\ @error: 1
[20:06:23] - /!\ @extended: 12006
[20:06:23] - /!\ Error Downloading File : \\wz-retro\roms\..\configs\all\emulationstation\downloaded_images\atarist\Adidas Championship Tie Break (Europe)-image.jpg
[20:06:23] - /!\ Bytes read: 0
[20:06:23] - /!\ Size: 0
[20:06:23] - /!\ Complete: True
[20:06:23] - /!\ successful: False
[20:06:23] - /!\ @error: 1
[20:06:23] - /!\ @extended: 12006
[20:06:24] - /!\ Error Downloading File : \\wz-retro\roms\..\configs\all\emulationstation\downloaded_images\atarist\Adidas Championship Tie Break (Europe)-image.jpg
[20:06:24] - /!\ Bytes read: 0
[20:06:24] - /!\ Size: 0
[20:06:24] - /!\ Complete: True
[20:06:24] - /!\ successful: False
[20:06:24] - /!\ @error: 1
[20:06:24] - /!\ @extended: 12006
[20:06:24] - > -In 3 try and 0.83s
```
So it claims the download does not work. Even more strange: In the config I lready replaced the part `\\wz-retro\roms\..\configs`with `\\wz-retro\configs`but it still tries to use `\\wz-retro\roms\..\configs`. Maybe that separate process "Scraper.exe" does not get the updated config from the main process?

**Comment by verybadsoldier** [comment] 2016-11-25 19:23
I could workaround it I think. I the autoconfig I see `\\wz-retro\configs\all\emulationstation\downloaded_images\%System%` but the file `UXS-config.ini`still contained:
```
$vTarget_XMLName=\\wz-retro\roms\..\configs\all\emulationstation\gamelists\atarist\gamelist.xml
$vSource_ImagePath=\\wz-retro\roms\..\configs\all\emulationstation\downloaded_images\atarist
```
Note the `roms\..\`. When I changed it manually there to:
```
$vTarget_XMLName=\\wz-retro\configs\all\emulationstation\gamelists\atarist\gamelist.xml
$vSource_ImagePath=\\wz-retro\configs\all\emulationstation\downloaded_images\atarist
```
Then it works again.

Maybe 2 problems? The path `\\wz-retro\roms\..\configs\all\emulationstation\downloaded_images\atarist` does not work correctly and also `UXS-config.ini` does not get updated correctly?

**Comment by Universal-Rom-Tools** [comment] 2016-11-26 12:09
sorry to answer so late...

This is how it work : 

In Profil XML you have the "autoconfiguration path" standard for retropit is : 
```
	<AutoConf>
		<Source_RootPath>\\retropie\roms</Source_RootPath>
		<Target_XMLName>%Source_RootPath%\..\configs\all\emulationstation\gamelists\%System%\gamelist.xml</Target_XMLName>
		<Target_RomPath>/home/pi/RetroPie/roms/%system%/</Target_RomPath>
		<Source_ImagePath>%Source_RootPath%\..\configs\all\emulationstation\downloaded_images\%System%</Source_ImagePath>
		<Target_ImagePath>/home/pi/.emulationstation/downloaded_images/%system%/</Target_ImagePath>
	</AutoConf>
```

Explaination : 
**Source_RootPath** is where UXS Autoconfig look for system folder
**Target_XMLName** is where UXS put the final gamelist.xml will be wrote
**Target_RomPath** is where emulationstation will found the rom (UXS put this path in gamelist.xml)
**Source_ImagePath** is where UXS will download picture (mix or not)
**Target_ImagePath** is where emulationstation will found the picture (UXS put this in gamelist.xml)

I added some "tag" that will be replace automatically : 
**%Source_RootPath%** will be replaced by the path in <Source_RootPath>
**%system%** will be replaced by the folder of the system you selected in autoconf
**%SystemDir%** will be a merge of %Source_RootPath%+%system%

Autoconf will replace path and put it in UXS-config.ini, when you select a system in the menu "scrape/select a system"
And the scrape use path in UXS-config.ini

So now if we examin the standard path : 
**Source_RootPath** = \\retropie\roms
**Target_XMLName** = %Source_RootPath%\..\configs\all\emulationstation\gamelists\%System%\gamelist.xml
-> If we select nes has system : 
\\retropie\roms\..\configs\all\emulationstation\gamelists\nes\gamelist.xml _(in UXS-config.ini)_
So : 
\\retropie\configs\all\emulationstation\gamelists\nes\gamelist.xml _(is the reel path /../ meaning 1 step behind)_
**Target_RomPath** = /home/pi/RetroPie/roms/%system%/
-> If we select nes has system : /home/pi/RetroPie/roms/nes/ _(in UXS-config.ini)_
**Source_ImagePath** = %Source_RootPath%\..\configs\all\emulationstation\downloaded_images\%System%
-> If we select nes has system : 
\\retropie\roms\..\configs\all\emulationstation\downloaded_images\nes _(in UXS-config.ini)_
So :
\\retropie\configs\all\emulationstation\downloaded_images\nes _(is the reel path /../ meaning 1 step behind)_
**Target_ImagePath** = /home/pi/.emulationstation/downloaded_images/%system%/
-> If we select nes has system : /home/pi/.emulationstation/downloaded_images/nes/  _(in UXS-config.ini)_

It's a little bit complexe... Sorry, but it's needed to "respect Retropie Path" and keep a simple way to configure path with changing only the **Source_RootPath**.
So if you want to scrape a USB Key having the "same" type of path, you juste have to change the _\\retropie\roms_ By _E:\\roms_ for exemple, and all other path will adapte themself...

Last but not least, the easiest way still to use Path like Sselph's scraper (or the path used in Recalbox) where all gamelist and downloaded picture are directly in the rom system folder.

That's why I create a new profil in the last version with [Sselph Path] : much much more easier ;)

**Comment by verybadsoldier** [comment] 2016-11-26 12:29
Thanks for the detailed explanation! But I think the path with ".." does not work for me as intended. I had to manually remove the ".." and enter the absolute path then it worked.
And also even after changing the path in the settings, the file `UXS-config.ini`still contained the old path (with "..") and it was still used.

**Comment by verybadsoldier** [comment] 2016-11-26 12:33
Maybe for RetroPie it would be easier to just enter the device name, in my case "wz-retro". Then UXS can build the ROM path "\\wz-retro\roms" and the config path "\\wz-retro\configs" from it. No need for ".." then.

**Comment by Universal-Rom-Tools** [comment] 2016-11-26 12:43
Did you "re select" the system after changing path ?

UXS-config.ini is updated only at the system selection.

For putting the "root path" I wanted, at start, to reduce the number of path configuration to the minimum... It may be confusing for a noob to configure manually lot's of path (with 5 it's already complexe ^^)

I need to check the /../ it works on my test :S

**Comment by verybadsoldier** [comment] 2016-11-26 12:50
I probably did not reselect the system I guess! Thanks for the hint!
I will retest ".." again here also.

**Comment by TuKo1982** [comment] 2016-11-26 14:19
Same for me, latest 2.0.0.3 doesn't work for me on RetroPie 4.1

**Comment by Universal-Rom-Tools** [comment] 2016-11-26 16:54
That's weird :S

I just retry, and it works for me :S

I haven't retropie, so I make a network directory on my nas named Retropie, and connect a netdrive on it... (just to simulate the retropie).

And I try to scrape

Do I have this : http://hpics.li/841835b

So for me it's ok :S (from my point of view :S)

Can you try delete the UXS folder, and download the [very last version](https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/releases) ? 
(I ask to delete the folder to be sure the "old" profil will be recreated)

**Comment by verybadsoldier** [comment] 2016-11-26 17:52
Just tested it again and I have to say for me really ".." does not work. A workaround for now is to go to "Autoconfiguration path configuration" and edit "XML file name" and "Folder name where pictures will be downloaded". Replace "%Source_RootPath%\..\configs" with "\\<host>\\configs*"

Important: After changing that you have to re-select the system in the menu "Select your system"!

**Comment by chewvodka** [comment] 2016-11-27 15:09
Confirmed to be working by replacing ``%Source_RootPath%\..\configs`` with ``\\<host>\\configs``.  I've been scraping all night and checking every other system or so and it's loading up in the correct paths just fine.

**Comment by Universal-Rom-Tools** [comment] 2016-11-27 17:28
I added a %host% variable in the last version.

Trying with : 

```
<AutoConf>
	<Source_RootPath>\\retropie\roms</Source_RootPath>
	<Target_XMLName>%host%\configs\all\emulationstation\gamelists\%System%\gamelist.xml</Target_XMLName>
	<Target_RomPath>/home/pi/RetroPie/roms/%system%/</Target_RomPath>
	<Source_ImagePath>%host%\configs\all\emulationstation\downloaded_images\%System%</Source_ImagePath>
	<Target_ImagePath>/home/pi/.emulationstation/downloaded_images/%system%/</Target_ImagePath>
</AutoConf>
```

so %host% = \\retropie and it's seems to work...

**Comment by verybadsoldier** [comment] 2016-11-27 19:00
It might be me but I don't see a new version and I don't see any commits in the master branch. The last commit is like 48 h ago?

**Comment by Universal-Rom-Tools** [comment] 2016-11-27 19:01
I'm compiling it right now ;) Release will come in a minute ;)

**Comment by Universal-Rom-Tools** [comment] 2016-11-27 19:10
Done ;) it's released ;)

**Comment by verybadsoldier** [comment] 2016-11-27 19:36
Thanks, works on my first tests!

**Comment by Universal-Rom-Tools** [comment] 2016-11-27 19:40
Great ^^

Let me know if I can close this issue ;)

**Comment by chewvodka** [comment] 2016-11-27 19:52
I will test as well, give me a few moments..

**Comment by TuKo1982** [comment] 2016-11-27 20:02
Works well now, fixed for me :)

**Comment by chewvodka** [comment] 2016-11-27 20:02
Looks good now here too!

**Comment by verybadsoldier** [comment] 2016-11-28 12:20
Some people confirmed the fix is working, I think you can close this, thanks! :)

**Comment by Universal-Rom-Tools** [comment] 2016-11-28 12:21
Great ^^ One big bug less :p

**Closed by Universal-Rom-Tools** 2016-11-28 12:21 UTC
Labels: question
